Cache website package metadata like GitHub ones

diff --git a/deb-get b/deb-get
--- a/deb-get
+++ b/deb-get
@@ -163,6 +163,19 @@ function get_github_releases() {
     fi
 }
 
+function get_website() {
+    METHOD="website"
+    if [ "${ACTION}" == "install" ] || [ "${ACTION}" == "update" ] || [ "${ACTION}" == "fix-installed" ]; then
+        if [ ! -e "${CACHE_DIR}/${APP}.html" ] || test "$(find "${CACHE_DIR}/${APP}.html" -mmin +60)"; then
+            fancy_message info "Updating ${CACHE_DIR}/${APP}.html"
+            if ! "${ELEVATE}" wget -q --no-use-server-timestamps "${1}" -O "${CACHE_DIR}/${APP}.html"; then
+                fancy_message warn "Updating ${CACHE_DIR}/${APP}.html failed. Deleting it."
+                ${ELEVATE} rm -f "${CACHE_DIR}/${APP}.html"
+            fi
+        fi
+    fi
+}
+
 function fancy_message() {
     if [ -z "${1}" ] || [ -z "${2}" ]; then
       return
@@ -374,7 +387,7 @@ function validate_deb() {
     export PPA=""
     export ARCHS_SUPPORTED="amd64"
     export CODENAMES_SUPPORTED=""
-    export METHOD="website"
+    export METHOD="direct"
     export EULA=""
     export URL=""
     export VERSION_INSTALLED=""
@@ -418,7 +431,7 @@ function validate_deb() {
     elif  [ -n "${PPA}" ]; then
         METHOD="ppa"
     else
-        if { { [ "${METHOD}" = github ] && [ -e "${CACHE_DIR}/${APP}.json" ]; } || [ "${METHOD}" != github ]; } &&
+        if { { [ "${METHOD}" == github ] && [ -e "${CACHE_DIR}/${APP}.json" ]; } || { [ "${METHOD}" == website ] && [ -e "${CACHE_DIR}/${APP}.html" ]; } || [ "${METHOD}" == direct ]; } &&
            { [ "${ACTION}" != "prettylist" ] && [ "${ACTION}" != "remove" ] && [ "${ACTION}" != "purge" ]; } &&
            { [ -z "${URL}" ] || [ -z "${VERSION_PUBLISHED}" ]; }; then
             fancy_message error "Missing required information of ${METHOD} package ${APP}:"
