deb-get: Catch failures when updating GitHub releases. Close #6

diff --git a/deb-get b/deb-get
--- a/deb-get
+++ b/deb-get
@@ -40,8 +40,12 @@ function get_github_releases() {
     if [ "${PRETTY}" -eq 0 ]; then
         fancy_message info "Updating ${CACHE_DIR}/${APP}.json"
         if [ ! -e "${CACHE_DIR}/${APP}.json" ] || test "$(find "${CACHE_DIR}/${APP}.json" -mmin +60)"; then
-            curl -s "${1}" > "${CACHE_DIR}/${APP}.json"
-            if grep "API rate limit exceeded" "${CACHE_DIR}/${APP}.json"; then
+            if ! wget -q "${1}" -O "${CACHE_DIR}/${APP}.json"; then
+                fancy_message warn "Updating ${CACHE_DIR}/${APP}.json failed. Deleting it."
+                rm "${CACHE_DIR}/${APP}.json" 2>/dev/null
+            fi
+            if [ -f "${CACHE_DIR}/${APP}.json" ] && grep "API rate limit exceeded" "${CACHE_DIR}/${APP}.json"; then
+                fancy_message warn "Updating ${CACHE_DIR}/${APP}.json exceed GitHub API limits. Deleting it."
                 rm "${CACHE_DIR}/${APP}.json" 2>/dev/null
             fi
         fi
