Add error code to error message

diff --git a/.github/workflows/tests-01-main.yml b/.github/workflows/tests-01-main.yml
--- a/.github/workflows/tests-01-main.yml
+++ b/.github/workflows/tests-01-main.yml
@@ -51,7 +51,7 @@ jobs:
               continue
             fi
             if ! ./deb-get install "${APP}"; then
-              echo "::error::App ${APP} failed to install" >&2
+              echo "::error::App ${APP} failed to install: error $?" >&2
               ((errors++))
               continue
             fi
@@ -68,7 +68,7 @@ jobs:
               # fallthrough
             fi
             if ! ./deb-get purge "${APP}"; then
-              echo "::error::App ${APP} failed to be purged" >&2
+              echo "::error::App ${APP} failed to be purged: error $?" >&2
               ((errors++))
             fi
           done
