chore(ci): simplify/enhance logic in tests-01-main.yml

diff --git a/.github/workflows/tests-01-main.yml b/.github/workflows/tests-01-main.yml
--- a/.github/workflows/tests-01-main.yml
+++ b/.github/workflows/tests-01-main.yml
@@ -45,22 +45,24 @@ jobs:
           APPS="$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep "^01-main/packages/" | sed "s|^01-main/packages/||")"
           SUPPORTED="$(./deb-get list --raw)"
           for APP in ${APPS}; do
-            if echo "${SUPPORTED}" | grep -q -m 1 "^${APP}$"; then
-              ./deb-get install "${APP}"
-              if ./deb-get show "${APP}" | grep -q "Installed:	No"; then
-                echo "Failed to detect ${APP} as installed" >&2
+            if ! grep -q -m 1 "^${APP}$" <<<"${SUPPORTED}"; then
+              echo "Skipping '${APP}' as it is not supported" >&2
+              continue
+            fi
+            ./deb-get install "${APP}"
+            if ./deb-get show "${APP}" | grep -q "Installed:	No"; then
+              echo "Failed to detect '${APP}' as installed" >&2
+              exit 1
+            fi
+              PUBLISHED_VER=$(./deb-get show "${APP}" | grep "Published:" | grep -oE '[^[:space:]]+$' || :)
+              INSTALLED_VER=$(dpkg-query -Wf '${Version}' "${APP}" || :)
+              if [ -n "${PUBLISHED_VER// /}" ] && dpkg --compare-versions "${PUBLISHED_VER}" gt "${INSTALLED_VER}" ; then
+                echo "Versions do not match. The '${APP}' package's VERSION_PUBLISHED variable may need to be changed." >&2
+                echo "Published Version: ${PUBLISHED_VER}"
+                echo "Installed Version: ${INSTALLED_VER}"
                 exit 1
-              else
-                PUBLISHED_VER=$(./deb-get show "${APP}" | grep "Published:" | grep -oE '[^[:space:]]+$' || :)
-                INSTALLED_VER=$(dpkg-query -Wf '${Version}' "${APP}" || :)
-                if [ -n "${PUBLISHED_VER// /}" ] && dpkg --compare-versions "${PUBLISHED_VER}" gt "${INSTALLED_VER}" ; then
-                    echo "Versions do not match. The package's VERSION_PUBLISHED variable may need to be changed." >&2
-                    echo "Published Version: ${PUBLISHED_VER}"
-                    echo "Installed Version: ${INSTALLED_VER}"
-                    exit 1
-                else
-                    ./deb-get purge "${APP}"
-                fi
               fi
+              
+              ./deb-get purge "${APP}"
             fi
           done
